version: '3'
services:
    user:
        restart: on-failure
        build: .
        container_name: user
        depends_on:
            - kibana
        ports:
            - "9213:9213"
            - "9212:9212"
    kibana:
        image: "kibana:7.6.2"
        container_name: kibana 
        depends_on:
            - elasticsearch
        ports:
            - "5601:5601"
    elasticsearch:
        image: "elasticsearch:7.6.2"
        container_name: elasticsearch
        environment:
            - "discovery.type=single-node"
        ports:
            - "9200:9200"
            - "9300-9300"
